### ISSUE TITLE
includes() not well supported in mobile, find another way

### ISSUE THREAD

**Issue by WardCunningham** [WardCunningham/remodeling#11]
Our check for available pages breaks rendering on some devices. We can adopt a future-oriented posture for this work. But if we want to fix it for the present, here is where we can find it.

https://github.com/WardCunningham/remodeling/blob/master/static/index.html#L126

**Comment by mattatobin** [comment]
If you want to use .includes or any other ES6+ feature you should use polyfills to ensure accessibility and compatibility just in case a specific nugget isn't implemented everywhere yet.
