### ISSUE TITLE
'topic name' links do not exist for categories 

### ISSUE THREAD

**Issue by finnoleary** [WardCunningham/remodeling#12]
The category pages say:

```
To find other topics in a given category, click on the topic name above. This should take you to a category page. 
```

however there is no such link present.

An example of this is http://wiki.c2.com/?HelpUsingCategories, but from what I have observed I believe that all categories have this fault.

**Comment by WardCunningham** [comment]
I've added this to the phase #2 goals.

**Comment by WardCunningham** [comment]
623abde adds this link which also makes the community devisied category mechanism work.

![image](https://cloud.githubusercontent.com/assets/12127/20032760/bb78fc54-a34e-11e6-971d-4b3520f7b0c5.png)
