### ISSUE TITLE
Using back button in browser sends me back to the top of the page

### ISSUE THREAD

**Issue by will-crawford** [WardCunningham/remodeling#14]
This breaks PoLA badly - I'm used to clicking on a link, reading the reference, and going back to the original page and finding myself about where I left off (usually roughly in the middle vertically :)).

**Comment by WardCunningham** [comment]
Federated wiki does this right. We should make this more like federated wiki.

**Comment by WardCunningham** [comment]
I've tested this on chrome, safari and firefox and found that it works correctly. This is not due to managing location state, but due to being simple links as in the early web. We will have to be careful when adding side-by-side viewing, but for now, I will close this issue.
