### ISSUE TITLE
Wiki requires JS for displaying static content

### ISSUE THREAD

**Issue by Tjoppen** [WardCunningham/remodeling#18]
Also known as "wiki does not work with lynx or TOR browsers". The latter is particularly important given the political direction of western nations. The wording "static site" in #2 seems to indicate this is a goal, but I don't see an explicit bullet point for this, hence this ticket

Example URL: http://wiki.c2.com/?InfiniteStateMachine  (via IRC)

**Comment by WardCunningham** [comment]
By "static site" I was referring to github pages or other like platforms serving only static content. I've revised the description to make this clear. I've separated the historic artifact, the text written by authors, from the rendering required to read it which I distribute as javascript. This might fit nicely into a node application if you can find someone willing to host it.

**Comment by iacunoijn** [comment]
This might come in handy to get the bare minimum functionality with the bare minimum dependencies and deployment hassle:

```python
# Quick and dirty C2 wiki proxy that allows viewing pages without
# needing client-side JavaScript, albeit with close to no functionality.

# Usage:
# $ wget http://bottlepy.org/docs/0.12/bottle.py
# $ python thisfile.py
# Then visit e.g. 'http://localhost:8080/AccessibleWebPageDesign'

import json
import urllib2

from bottle import route, run, template

@route('/<page>')
def page(page):
    root = 'http://c2.com/wiki/remodel/pages/'
    body = json.load(urllib2.urlopen(root + page))['text']
    body = body.replace('\n', '<br>')

    tmpl = """<html><head><title>{{page}}</title></head>
<body><h1>{{page}}</h1>%s</body></html>""" % body

    return template(tmpl, page=page)

run(host='localhost', port=8080, debug=True)
```

**Comment by Tjoppen** [comment]
That mirror doesn't render the pages to HTML tho, so there's no links. Not very WWW! :)

Maybe if I care enough I'll set up a static mirror of my own

**Comment by winny-** [comment]
It is unfortunate JS is necessary to view the original site. Thankfully archive.org's Wayback Machine has the site before the change:

- [Front Page](https://web.archive.org/web/20161003210837/http://c2.com/cgi/wiki)
- [List of all pages](https://web.archive.org/web/20160828233301/http://c2.com/cgi/wiki?search=$)

Unfortunately WikiWikiWeb ratelimited archive.org's crawler with a [200 response](https://archive.org/wayback/available?url=https%3A//c2.com/cgi/wiki%3FDrScheme) which didn't indicate to the crawler of the error condition retrieving content. [Example bad capture](https://web.archive.org/web/20160716195545/https://c2.com/cgi/wiki?DrScheme). To get around this, you will have to visit the site at a different crawl time. [Example good capture](https://web.archive.org/web/20160709121845/http://c2.com/cgi/wiki?DrScheme).

**Comment by neauoire** [comment]
I've been using the wayback machine to browse wiki.c2 since the migration, but I just wanted to check-in, is there any plan of making it available without javascript again? 

I can't help but feel like for all the good knowledge found on this wiki, very little of the past hard-earned lessons that it documents, has advised this migration.

**Comment by kluvin** [comment]
> I've been using the wayback machine to browse wiki.c2 since the migration, but I just wanted to check-in, is there any plan of making it available without javascript again?
> 
> I can't help but feel like for all the good knowledge found on this wiki, very little of the historical hard-earned lessons that this site documents, has advised this migration.

I have been working on converting the markup to markdown, and rendering that to semantic HTML on the server-side on and off for some time now.

Most pages work, current effort is to implement a way to edit articles without fear of edit wars.

It’s over at https://gitlab.com/kluvin/wiiiki if you’re interested.

**Comment by OT7EtoYoshimura** [comment]
checks out for someone maintaining the ***fed***wiki lol
