### ISSUE TITLE
NoScript support?

### ISSUE THREAD

**Issue by WillemMali** [WardCunningham/remodeling#21]
wiki.c2.com used to load very quickly and work with JS disabled, but now it doesn't. It loads slow (~7 seconds), I see a spinning wheel of death, it doesn't seem to cache pages, and I have to spend time whitelisting it in uMatrix (I don't run scripts normally).

Do you have plans for a version that works without scripts, perhaps just read-only?

A few groups of users that would benefit from this:
* Security-minded users with a script whitelisting policy (e.g. me)
* Users with esoteric browsers with bad/no JS support
* Visually impaired users with screen readers, which don't always have JS support
* Users with principal objections against running non-FLOSS code
* Users running TOR (The Browser Bundle has NoScript enabled by default for security)
* Search engine crawlers
* Users with a CURL workflow (e.g. Richard Stallman)

If not, could you provide a method of downloading an archive of the wiki, so there is a way of reading the wiki without scripts?

No offense intended, I like the idea of the federated wiki (and the more general exploration of web decentralization) and love its content, I just want to read it in HTML/XHTML/JSON/TXT/YML or any other format that does not require me to run unknown code and patch together the page on-the-fly.

**Comment by WardCunningham** [comment]
Our intention is to serve the json from a cdn and then offer small revisions to the javascript in this repo for rendering it. The json represents the historic artifact. You are welcome to devise other means of rendering it but I discourage you from download all json pages as they are not yet complete as noted elsewhere in these issues.

**Comment by WillemMali** [comment]
That definitely works for, is that JSON available publicly yet? I'd like to set up a basic static site generator for it. Perhaps I can make it request only the JSON for pages requested, and only when the TTL of the cached copy has run out. 

I'm assuming the JSON files are dynamic because it's a wiki, shouldn't that make OK for me to get some broken ones? I'll have to set up my server to sanely cache and re-request the JSON anyway.

**Comment by timmc** [comment]
Is there no static site remaining anymore? I'm sad to see the c2 wiki app-ified. :-(
