### ISSUE TITLE
Could you remove my page?

### ISSUE THREAD

**Issue by fgenolini** [WardCunningham/remodeling#23]
Please delete my page:

http://wiki.c2.com/?FrancoisGenolini

**Comment by WardCunningham** [comment]
Not stored here.

**Comment by fgenolini** [comment]
Hi,  Thanks for the reply.

There is a piece of text at the bottom of the page that says:
`
Last edit June 15, 2003, See github about remodling.
`

Since there is no edit function on that page (no "Edit Page" icon or link), that led me to believe that this page could be removed / edited using github.

Regards,

Francois Genolini

**Comment by WardCunningham** [comment]
Ah. I see the confusion. I'll change that wording.

I am rapidly loosing the ability to make changes, including deletions. In your case I will see what I can do.
