### ISSUE TITLE
invalid criticisms

### ISSUE THREAD

**Issue by cwkatzmann** [WardCunningham/remodeling#35]
The discussion displayed [here](http://wiki.c2.com/?Desig) and continued [here](http://wiki.c2.com/?CrudIsForBeginners) is a complete waste of time, and an abject distraction, due to the failure of the questioner to understand not only the purpose of the book, but why instructional books in general cannot cannot contain specific examples of how any given reader could apply the general instruction to their specific domain of choice. 

I mean, come on. If instructional books had to live up to the questioner's stated expectations, all instructional books would contain far too much information to be practical, let alone useful in any way.

If this person was serious about their criticisms, they must be a very unique individual, as many of their concerns are not of the kind the vast majority of readers would ever consider.

My request is to remove these criticisms, as they appear to be the work of either an uninformed person, or an intentionally controversial person, or a person with an uncommon and unique mind which 
most readers would not be able to relate to. In my opinion, and despite its undeniable comedic value, the material in question does not belong where it now lies.

**Comment by WardCunningham** [comment]
You could be right. And this might be a historically significant example of early wrong thinking on the internet. Although I remember the advocate of table oriented programming (TOP) who may have set an earlier precedent as he criticised every other idiom with tremendous energy.
