### ISSUE TITLE
Proper author attributes

### ISSUE THREAD

**Issue by Sawtaytoes** [WardCunningham/remodeling#36]
I'm writing an article and will be quoting parts of this Wiki. Would you be able to provide me with the names of those who wrote it or at least the name of the Wiki (WikiWikiWeb?) so I can properly attribute authors?

I'm specifically writing on Message Oriented Programming and am looking at these pages:
- http://wiki.c2.com/?MessageOrientedProgramming
- http://wiki.c2.com/?DynamicDispatch
- http://wiki.c2.com/?AlanKay
- http://wiki.c2.com/?AlanKayOnMessaging

**Comment by WardCunningham** [comment]
This original wiki did not keep track of authorship other than what authors might provide within the text they wrote. Some portions had many authors who remain unacknowledged. Also the computer keep track of the most recent modification date but not the date of first published article.

This is the best advice we have.
http://wiki.c2.com/?HowToCiteWiki
