### ISSUE TITLE
single page view way too slow

### ISSUE THREAD

**Issue by WardCunningham** [WardCunningham/remodeling#4]
We fetch a list of valid internal link names so that we don't send the viewer down dead ends. This involves 1000 msec of text transfer that we must speed up or eliminate. 

![image](https://cloud.githubusercontent.com/assets/12127/19414157/e4e24886-92f8-11e6-8448-1c3f7c91de18.png)

We can reduce our longest transfer time by gzipping the names in a build. Here we see a factor of three improvement. Not so impressive.

![image](https://cloud.githubusercontent.com/assets/12127/19414141/88b584b0-92f8-11e6-92be-8ec329edd91f.png)

Another approach might be to lookup every link while reformatting the page records. Once in json we could include a list of valid (or invalid) links present on the page.

**Comment by nateberkopec** [comment]
FWIW, `zopfli` crushes the names text file down to 228kB. IMO, 228kB with a long cache lifetime is not the end of the world.

However, instead of blocking rendering on the download of this file, you might consider displaying the page with no links, then creating link elements once names.txt has loaded. Not sure if that would work.

**Comment by fquist** [comment]
Would it be possible to programmatically check the status of links at the server side, and then send a list containing only the valid links along with the primary JSON response as a validlinks property? The client-side could then use it to do what it needs to do to prevent bumping into dead ends. This would eliminate most text transfer and one roundtrip.

**Comment by WardCunningham** [comment]
@fquist, preprocessing is an attractive approach especially since the content is unchanging. We could identify both inbound and outbound links with the json payload for each page. Inbound links provide the "who links here" functionality offered as a link property of the page title.

The full names.txt list does provide additional search capability which we enjoy. I don't think we want to lose that. Preprocessing of that file could include inbound links too, possibly encoded as integer indices into the names array.

**Comment by WardCunningham** [comment]
Experience has shown that caching and overlapped i/o makes the current code fast enough.

![image](https://cloud.githubusercontent.com/assets/12127/20239619/3dbf0c5c-a8b9-11e6-9ef9-fbc52421eb09.png)
