### ISSUE TITLE
does not load without js

### ISSUE THREAD

**Issue by brightersun99** [WardCunningham/remodeling#48]
I don't get this insanity. 

This website is presented as light weight and text only, at least at a glance.

Yet without JS the entire site is inaccessible, it just sits at loading.

That is dumb as hell, please add a fallback for no js or better yet don't do such crappy web development practices.

Making a website's content totally inaccessible without js is such an incompetent thing to do, god

**Comment by WardCunningham** [comment]
Ah, but the incremental search is awesome. Try it out.

**Comment by WardCunningham** [comment]
See 823ee1443be377fb159da480eb4037c5788180d5 as recommended by a colleague who though brightersun99 might be confused.

![image](https://user-images.githubusercontent.com/12127/96287466-d7810500-0f96-11eb-9263-7af384d37a30.png)
