### ISSUE TITLE
wiki.c2.com seems down: 502 Bad Gateway

### ISSUE THREAD

**Issue by soundasleep** [WardCunningham/remodeling#52]
Trying to go to any page (including the home page) is returning:

> Trouble Encountered
> https://proxy.c2.com/wiki/remodel/pages/WhatIsRefactoring
> can't fetch document
> 
> See github

Network Tools says that the page is returning 502 Bad Gateway.

And because the entire site is a SPA there's no way to use Google Cached to see the content either... :(

**Comment by WardCunningham** [comment]
We see no evidence of problem on the c2.com server. Current thoughts is to move javascript into the edge so that the haters don't have to deal with it.
