### ISSUE TITLE
Problem on https://wiki.c2.com/?ConsiderTheSource

### ISSUE THREAD

**Issue by FordPrefect1024** [WardCunningham/remodeling#56]
This particular page : "https://wiki.c2.com/?ConsiderTheSource"(accessed 9/13/2021) ends up ranking pretty high on Google's search results (congrats!), but it seems to confuse how to commit the fallacy with the definition of it.... and is followed by some opinions that, while I'm sure belong to the attributed folks, are in in error and/or reference other fallacies--also wrongly.... What appear to be opinions have factual errors of their own (e.g. ad hominem is where you attack the source of the statement/proposition, vs the actual statement/proposition.)  

It may be appropriate to remove the inaccurate material, or easier, insert a disclaimer or link to a reputable source.

Thanks.

**Comment by WardCunningham** [comment]
This site is frozen as a historic artifact. The decades of opportunity to correct errors have passed.
